import roomsData from './data/rooms.json';
import { visualSignature } from './signature';
import { normalizeName } from './game/matching';
import type { Area, RenderSettings, Room } from './types';

// Generated by `npm run build:data` and committed, so the app needs no build step to run.
// tests/corpus.test.ts fails if this file drifts from data/raw.
const rooms = (roomsData as { rooms: Room[] }).rooms;

const byId = new Map(rooms.map((r) => [r.id, r]));
const byNameKey = new Map<string, Room>();
for (const room of rooms) {
  for (const name of [room.name, ...room.aliases]) byNameKey.set(normalizeName(name), room);
}

/** Every room, in id order. */
export function loadRooms(): Room[] {
  return rooms;
}

export function roomById(id: number): Room | undefined {
  return byId.get(id);
}

/** Looks up a room by canonical name or alias, tolerant of case and punctuation. */
export function roomByName(name: string): Room | undefined {
  return byNameKey.get(normalizeName(name));
}

export function roomsInArea(area: Area): Room[] {
  return rooms.filter((r) => r.area === area);
}

// Signatures depend on settings, so one cache per distinct settings object keeps repeated
// lookups during a session cheap without precomputing every combination.
const groupCache = new Map<string, Map<string, Room[]>>();

function groupsFor(settings: RenderSettings): Map<string, Room[]> {
  const cacheKey = JSON.stringify(settings);
  const cached = groupCache.get(cacheKey);
  if (cached) return cached;

  const groups = new Map<string, Room[]>();
  for (const room of rooms) {
    const key = visualSignature(room, settings);
    const group = groups.get(key);
    if (group) group.push(room);
    else groups.set(key, [room]);
  }
  groupCache.set(cacheKey, groups);
  return groups;
}

/**
 * Interiors whose icon fills the whole tile, border included. render_tile skips a tile's
 * edges when it carries one, so these draw no wall and no door.
 */
const ICON_INTERIORS = new Set([
  'saveStation', 'mapStation', 'energyRefill', 'ammoRefill', 'doubleRefill', 'ship',
]);

/**
 * Whether there is anything on screen to identify this room by.
 *
 * A room made only of station icons draws no geometry at all, so every save room looks
 * exactly like every other one. Asking about them is unanswerable rather than hard.
 */
export function isGuessable(room: Room): boolean {
  return room.tiles.some((t) => !ICON_INTERIORS.has(t.interior));
}

/** The rooms worth asking about. Every room stays answerable; these are the ones shown. */
export function guessableRooms(): Room[] {
  return rooms.filter(isGuessable);
}

/**
 * Every room that looks identical to this one at these settings, including itself.
 *
 * This is what a name answer is graded against: when two rooms paint the same pixels there
 * is no information on screen that could separate them, so both are right.
 */
export function equivalenceGroup(room: Room, settings: RenderSettings): Room[] {
  return groupsFor(settings).get(visualSignature(room, settings)) ?? [room];
}
